name             'sprout-jetbrains-editors'
maintainer       'Pivotal'
maintainer_email 'sprout-maintainers@pivotallabs.com'
license          'MIT'
description      'Recipes for installing Pivotal IDE preferences for Jetbrains editors on OSX'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
supports         'mac_os_x'
depends          'sprout-base'
depends          'sprout-homebrew'
